# Generated by Django 4.0.4 on 2024-06-22 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField(validators=[service.models.validate_time_in_hours])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=service.models.sports_complex_image_file_path)),
                ('location', models.CharField(choices=[('Kyiv', 'Kyiv'), ('Lviv', 'Lviv'), ('Odesa', 'Odesa')], default='Kyiv', max_length=10)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='SportsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Badminton', 'Badminton')], default='Football', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='service.sportscomplex')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('session_url', models.URLField(default='http://127.0.0.1:8000', max_length=1000)),
                ('session_id', models.CharField(default=1, max_length=255)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='service.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='service.sportsfield'),
        ),
        migrations.AddField(
            model_name='booking',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
