# Generated by Django 4.0.4 on 2024-06-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hours_slots',
        ),
        migrations.AlterField(
            model_name='sportscomplex',
            name='location',
            field=models.CharField(choices=[('Kyiv', 'Kyiv'), ('Lviv', 'Lviv'), ('Odesa', 'Odesa')], default='Kyiv', max_length=10),
        ),
        migrations.AlterField(
            model_name='sportsfield',
            name='activity',
            field=models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Badminton', 'Badminton')], default='Football', max_length=10),
        ),
    ]
