# Generated by Django 4.0.4 on 2024-06-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportground',
            options={},
        ),
    ]
